FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["211system/211system.csproj", "211system/"]

RUN dotnet restore "211system/211system.csproj"

COPY . .

WORKDIR "/src/211system"

RUN dotnet build "211system.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "211system.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

COPY --from=publish /app/publish .

EXPOSE 8080
ENV ASPNETCORE_HTTP_PORTS=8080

ENTRYPOINT ["dotnet", "211system.dll"]